[package]
name = "markdown-rs"
version = "0.1.0"
authors = ["Nil Gradisnik <nil@layer.com>"]
description = "Fast, simple, distraction free Markdown editor."
repository = "@nilgradisnik/markdown-rs"
readme = "README.md"
license = "MIT"

[dependencies]
gio = "0.3"
sourceview = "0.3"
comrak = "0.2"
horrorshow = "0.6"
webkit2gtk = "0.3"

[dependencies.gtk]
version = "0.3"
features = ["v3_20"]

[dev-dependencies]
clippy = "0.0.175"
